name: Test
"on":
  push:
    branches:
      - master
      - beta
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test_matrix:
    strategy:
      matrix:
        node-version:
          - '14.17'
          - 16
          - 18
          - 20
          - 22
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - name: Ensure dependencies are compatible with the version of node
        run: npx ls-engines
#      - run: npm run test:ci
      - run: npm run lint
